### PR TITLE
NewClass12: Request new Class New Class 12

### PR DESCRIPTION
**Pull request by bergos**
class 12

### CODE REVIEW

**Comment by l00mi** [comment]
test test

**Comment by l00mi** [comment]
[[Foo Team]]
---
test

**Comment by l00mi** [comment]
test2

**Comment by liamforde27** [comment]
here are my thoughts which are now changed

**Comment by liamforde** [comment]
here are my thoughts as an admin user

**Comment by liamforde** [comment]
[[TCF Official]]
---
and now with official answer

**Pull request closed without merging**
