### PR TITLE
NewClass4: Request new Class New Class 4

### PR DESCRIPTION
**Pull request by bergos**
I want it!

### CODE REVIEW

**Comment by vhf** [comment]
[[Foo Team]]
---
hello

**Comment by l00mi** [comment]
hello victor, how are you doing on this sunny day?

**Comment by l00mi** [comment]
sdfdsf
======

  

sdfdsf
------

**Comment by vhf** [comment]
salut
=====

https://github.com/tcfassociation/tcf-ontology-dev/issues/44

**Comment by hasseromer** [comment]
great proposal

**Pull request closed without merging**
